sources:
  
 # - name: MyGraphQLApi
 #    handler:
 #     graphql:
 #       endpoint: http://my-service-url:3000/graphql

 # - name: MyApi
 #   handler:
 #     jsonSchema:
 #       baseUrl: https://some-service-url/endpoint-path/
 #       operations:
 #         - type: Query
 #           field: users
 #           path: /users
 #           method: GET
 #           responseSchema: ./json-schemas/users.json

  - name: AlternateCms
    handler:
      postgraphile:
        connectionString: postgres://postgres:Libra1986@localhost/alternatecms

#  - name: CountryInfo
#    handler:
#      soap:
#        wsdl: http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL

#  - name: Employees
#    handler:
#      mysql:
#        host: localhost
#        port: 3306
#        user: root
#        password: passwd
#        database: employees